[package]
name = "lz4a"
version = "0.1.0"
authors = ["Dmitry Dulesov <dmitry.dulesov@gmail.com>"]
edition = "2018"

[dependencies]
libc = "0.2"

[build-dependencies]
cc = "1.0.54"

[dev-dependencies]
rand = "0.7.3"